version: "3"
services:
  app:
    image: hrconvert2:latest
    container_name: hrconvert2
    restart: always
    ports:
      - 8086:80
    volumes:
      - ./config.php:/var/www/html/HRProprietary/HRConvert2/config.php
